### ISSUE TITLE
concerns on parallel run

### ISSUE THREAD

**Issue by saikrishna321** [rajdeepv/parallel_calabash#1]
Hi,

Does the test run in parallel with different devices or can we run different tests on different devices?

**Comment by rajdeepv** [comment]
You can run different tests in parallel on different devices...Its dividing tests across devices to reduce the build time of your test suite.

**Comment by saikrishna321** [comment]
@rajdeepv thats a kool stuff..i was looking for something similar.. currently i user brew parallel 

How are the test distributed? lets say 3 devices and i have 3 features i would want each feature to run on each device .... how does this happen?

**Comment by rajdeepv** [comment]
Thanks @saikrishna321 .

Its simple. connect 3 devices to your computer. Assuming you have following feature files in features/  folder: first.feature , second.feature, third.feature

you just need to do this:
bundle exec parallel_calabash -a path/to/your.apk  features/ 

it will run first.feature on device1 , second.feature on device2 and third.feature on device 3

when all processes are done, it will summarize results at the end.

If you want to run all 3 features on device1, device2 and device3 simultaneously, this is not supported yet. I am planning to add that later.

**Comment by saikrishna321** [comment]
@rajdeepv  how will the test distribute when i have 10 features and 6 device connected ?

**Comment by saikrishna321** [comment]
send u a request on hangouts... would b good if u come over there ..

**Comment by rajdeepv** [comment]
It will divide 10 feature files in group of [2,2,2,2,1,1] i.e total 6 groups and each group will be executed on each device

**Comment by rajdeepv** [comment]
e.g if you have following files:
1.feature
2.feature
3.feature .....
.....
10.feature

Then you will see follwing execution:
Device1- ["test_files/1.feature", "test_files/6.feature"]
Device2 - ["test_files/10.feature", "test_files/7.feature"]
Device3 -  ["test_files/2.feature", "test_files/8.feature"]
Device4 - ["test_files/3.feature", "test_files/9.feature"]
Device5 -  ["test_files/4.feature"]
Device6 -  ["test_files/5.feature"]]

**Comment by rajdeepv** [comment]
for device specific data, you can use ENV['TEST_PROCESS_NUMBER'].

sample code to use different login credentials for different devices:

this is how your login_steps.rb might look like.

def credential_pool
  {'1' => 'user1/pass1', '2' => 'user2/pass2', '3' => 'user3/pass3'}
end

def credentials_for_current_device
  credential_pool[ENV['TEST_PROCESS_NUMBER']].split('/')
end

Given(/^I am logged-in user"$/) do
  query("\* id:'login'", :setText => credentials_for_current_device[0])
  query("\* id:'password'", :setText => credentials_for_current_device[1])
  # press login button
end

Thanks,
Rajdeep

**Comment by saikrishna321** [comment]
@rajdeepv thanks mate. will give it a try.

**Comment by saikrishna321** [comment]
@rajdeepv w.r.t reports,when i connect 3 devices, i will get 3 reports will these reports be concluded to a single report or it will remain different as before

**Comment by rajdeepv** [comment]
It will remain 3 different reports. No merging logic written yet
