### ISSUE TITLE
'No such file or directory' while running android tests in parallel

### ISSUE THREAD

**Issue by izhilenkov** [rajdeepv/parallel_calabash#15]
I have some problems while running calabash-android tests in parallels.
I use

```
parallel_calabash -a android_apps/some.apk -o '-p android' --concurrent features/some.feature
```

where **-p android** is 

```
'PLATFORM=android -r features/support -r features/android -r features/step_definitions -r features/android/pages' 
```

And next I have a following stacktrace

```
*******************************
 2 DEVICES FOUND
*******************************
No such file or directory - @smoke. Please create a @smoke directory to get started. (Errno::ENOENT)
No such file or directory - @smoke. Please create a @smoke directory to get started. (Errno::ENOENT)
```

Where **@smoke** is a tag in my feature file.

**Comment by rajdeepv** [comment]
@izhilenkov 
1. Are you able to run tests normally without using parallel_calabash ?
2. Can you give complete console log?

**Comment by izhilenkov** [comment]
@rajdeepv 
1. yep, tests work fine when i use "calabash-android"
2. 

```
*******************************
 2 DEVICES FOUND
*******************************
No such file or directory - And. Please create a And directory to get started. (Errno::ENOENT)
No such file or directory - @bigsmoke. Please create a @bigsmoke directory to get started. (Errno::ENOENT)

****** PROCESS 1 COMPLETED ******


****** PROCESS 0 COMPLETED ******




************ FINAL SUMMARY ************

Took 0 Minutes, 3.35 Seconds

```

It's seems like parallel_calabash try to read me feature file and use some keywords

**Comment by rajdeepv** [comment]
@izhilenkov I think I see what the issue is. I will try to reproduce it tomorrow and fix. Can you try using version 0.1.3 and see if works?

**Comment by rajdeepv** [comment]
@izhilenkov , I have fixed it. Please update your gem to latest version v0.2.3
Thanks

**Comment by izhilenkov** [comment]
@rajdeepv yeap, it's work awesome. thank you!

**Comment by rajdeepv** [comment]
Thanks
