### ISSUE TITLE
Tests distribution based on "feature" files

### ISSUE THREAD

**Issue by SergiyBeno** [rajdeepv/parallel_calabash#24]
Hello @rajdeepv and @sleekweasel 
First of all I want to thank you guys for your great work upon this project - nicely done :+1:
The only question that still confuses me is the tests distribution.
Can you explain how exactly **--distribution-tag tag** works ? How can we divide features using only 1 tag ? Can you add some info about this under Wiki section ? Thank you advance.
Or can you advise me how can I set distribution mode based on feature files ? For example I'd like to split all available feature files into 2 separate groups and run them using 2 iOS simulators (each simulator gets its own set of features) ? 
Should I use some `weighing_factor` ? 
If you have some manuals or tutorials can you pin them under Wiki section ? Thank you advance once again.

**Comment by rajdeepv** [comment]
@SergiyBeno Thanks for your question
1) --distribution-tag was added to distribute features files equally, based on occurrence of a perticular cucumber tag. It was inefficient and hence I removed the reference from wiki. To have better distribution of the tests, another flag --group-by-scenarios was introduced.
2) If you want to split all 'feature files' equally, you do not need to specify any flag. If you want to split all 'scenarios' equally, you need to use --group-by-scenarios. Each simulator will get its own features/scenarios by default.
3) As of now, readme file is the only reference.

**Comment by SergiyBeno** [comment]
Hi again @rajdeepv 
Thank you for your fast reply. 
Roger that. Closing this question.
