### ISSUE TITLE
Xcode 8 update (removed UIAutomation from Xcode 8)

### ISSUE THREAD

**Issue by SergiyBeno** [rajdeepv/parallel_calabash#27]
Hello @rajdeepv
You probably you already know that Apple has removed UIAutomation from Xcode 8. Will it affect the gem performance ?

**Comment by nmhoang2909** [comment]
Hi @SergiyBeno 
Have you ever tried calabash-parallel for ios with Xcode < 8 ?
Is it possible to run multiple simulators on one machine ? 
I have spent a lot of time to setup-ios but still not working now.

**Comment by SergiyBeno** [comment]
Hi @nmhoang2909 
Yes, sure - I've been using it for a couple month successfully without any problems in conjunction with Xcode 7.3. Yes, I remember that setup wasn't that easy but possible. Very useful tool :+1:

**Comment by bkarthick** [comment]
Hi @SergiyBeno,

Can you please share detailed setup steps to config calabash-parallel for ios It really helpful us.

**Comment by SergiyBeno** [comment]
I used instruction from README section and corrected some user permissions using chmod instruction.
