### ISSUE TITLE
"PROCESS 0 COMPLETED" even though found "3 DEVICES"

### ISSUE THREAD

**Issue by nmhoang2909** [rajdeepv/parallel_calabash#28]
Hi @rajdeepv 

I'm a newbie in Calabash, I'm trying to run multiple simulators for my iOS project but found this issue, I have researched this but still not working, could you please advise me some reasons ?

Name:project_calabash Name$ bundle exec parallel_calabash --app prebuilt/app-staging-release_cal.app --ios_config ~/.parallel_calabash.iphonesimulator --cucumber_opts '-p ios' features/integration/login.feature 

2016-10-07 18:21:07.831 instruments[10714:70215] WebKit Threading Violation - initial use of WebKit from a secondary thread.

---

3 DEVICES FOUND:
{:USER=>"tester1", :CALABASH_SERVER_PORT=>28000, :INIT=>"source \"$HOME/.rvm/scripts/rvm\""}
{:USER=>"tester2", :CALABASH_SERVER_PORT=>28001, :INIT=>"source \"$HOME/.rvm/scripts/rvm\""}
{:USER=>"tester3", :CALABASH_SERVER_PORT=>28002, :INIT=>"source \"$HOME/.rvm/scripts/rvm\""}

---

Running with 1 threads: [["features/integration/login.feature"]]
Delete: Entry, "CalabashServerPort", Does Not Exist
User app: prebuilt/tester1/app-staging-release_cal.app
Devices: 
Double check...
Devices: 
OK if none
Usage: simctl create <name> <device type="" id=""> <runtime id="">
0>> Device: = PCal-tester1 = PCal-tester1 (0.0)
PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.097 ms

--- localhost ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.097/0.097/0.097/0.000 ms
0>> Command: ssh tester1@localhost bash -lc "AUTOTEST='1';export AUTOTEST;DEVICE_ENDPOINT='http://localhost:28000';export DEVICE_ENDPOINT;DEVICE_TARGET='PCal-tester1 (0.0)';export DEVICE_TARGET;DEVICE_INFO='';export DEVICE_INFO;TEST_USER='tester1';export TEST_USER;TEST_PROCESS_NUMBER='1';export TEST_PROCESS_NUMBER;SCREENSHOT_PATH='PCal_1_';export SCREENSHOT_PATH;source "$HOME/.rvm/scripts/rvm";cd /Users/Name/Documents/Projects/project_calabash;umask 002;bundle exec cucumber APP_BUNDLE_PATH=prebuilt/tester1/app-staging-release_cal.app -p ios features/integration/login.feature" 2>&1
0> bash: /Users/Name/.rvm/scripts/rvm: Too many levels of symbolic links
0> bash: line 0: cd: /Users/Name/Documents/Projects/project_calabash: Permission denied
0> bash: bundle: command not found

*****\* PROCESS 0 COMPLETED ******

Writing log /tmp/PCal-tester1.process_number
[0]
All threads complete

***********\* FINAL SUMMARY ************

Took 0 Minutes, 13.78 Seconds
Parallel run complete

**Comment by nmhoang2909** [comment]
Hi @sleekweasel Could you help please ?

**Comment by sleekweasel** [comment]
The problem looks to be here:

bash: /Users/Name/.rvm/scripts/rvm: Too many levels of symbolic links

I'm guessing you used the set-up script. I think you might not have installed rvm for the first user, so it's trying to use a link to a link.

Use 'ls -l' (that's ell, not one) to look at the .rvm directory for the users, and remove the one they're pointing to. Then install rvm for as that user from the rvm website.

Once rvm works on the command line for each of the users, that bit should work.

You also need to make your project_calabash directory available to all your test users: each of those directories needs to be publicly readable, and the last needs to be publicly writeable too.

Once your test users can create files in there, from the command line (or desktop) it should be better.
