### ISSUE TITLE
Parallel Calabash dont identifies devices with android 4.1.x or less

### ISSUE THREAD

**Issue by mbnetobr** [rajdeepv/parallel_calabash#3]
I have this problem with device running android 4.1.x. Parallel Calabash dont identifies the device.

My environment
Calabash: Last version
Parallel Calabash: Last version
OS : Windows 7 Professional

**Comment by rajdeepv** [comment]
can you paste output of 'adb devices' command? Also, are you seeing this only for 4.1 devices and not others?

**Comment by mbnetobr** [comment]
Hi raj, in this case 'adb devices' return all devices normally.

For example if i'm have 2 devices connecteds:
- S3 with android 4.1.2
- S4 with android 4.2.2

Adb devices turn two devices on terminal.
But when i`m run command with parallel, only S4 is identified.

**Comment by rajdeepv** [comment]
Looks interesting, as I internally parse output of 'adb devices' to detect devices. I tried it but could not reproduce. It will help if you can send me screenshot of 'adb devices' output. Or can you please copy-paste exact output here?

**Comment by mbnetobr** [comment]
Hi raj,

See this screenshot.

![screenshot053](https://cloud.githubusercontent.com/assets/10273861/6563036/76ac788e-c674-11e4-8844-7a511bea0f9d.jpg)

**Comment by rajdeepv** [comment]
interesting. I have htc 4.1 device and it works with that. I do not have s3 though. I think there is something going wrong in parsing the output. can you run this in irb and let me know the output?
`adb devices`.scan(/\n(.*)\t/).flatten

eg:
2.1.1 :010 > `adb devices`.scan(/\n(.*)\t/).flatten
 => ["FA42RMW00506", "4d00fa3cb814c03f"]

**Comment by mbnetobr** [comment]
I return to work next week and give  feedback.

**Comment by saikrishna321** [comment]
@rajdeepv @mbnetobr  i hold an S3 with 4.1 and it works fine. I'm running parallely on S3(4.1),S4,Note 3,S5 and Nexus 5

**Comment by saikrishna321** [comment]
@rajdeepv i think @mbnetobr hold only one feature with @sanity tag, i have noticed the same over my side if no of device and no of scenarios should take the right permutations.. For example: 4 devices and 15 features parallel_calabash will tell 3 Devices Found

**Comment by mbnetobr** [comment]
@rajdeepv the output, in this case device with 4.1.2 version is "e78a7cc1"

irb(main):001:0> `adb devices`.scan(/\n(.*)\t/).flatten
=> ["cbd168d0", "e78a7cc1"]
irb(main):002:0>

I'm think the problem occurs only on windows.

**Comment by rajdeepv** [comment]
It seems like I need to handle parsing of output differently on windows. I don't have a windows machine as of now, but one last thing you can let me know is output of this in irb:

1.9.3-p0 :001 > `adb devices -l`.split("\n").collect{|line|  [line.split(" ").first,line.scan(/model:(.*) device/).flatten.first] if line.include?("device ")}.compact

**Comment by mbnetobr** [comment]
Show this:
[["cbd168d0", "SM_G800H"], ["4100980b7904cf00", "GT_I9082L"]]

**Comment by mbnetobr** [comment]
The second ID is android 4.1.x

**Comment by rajdeepv** [comment]
@mbnetobr looks like the features with sanity tags are not getting filtered correctly. A better option is to upgrade to latest version and run this command:

parallel_calabash -a your_apk_path -o'-r features' features/test/sanity  --group-by-scenarios --serialize-stdout

**Comment by mbnetobr** [comment]
I'm update version of the parallel_calabash and bug dont occurs.

Thanks raj.

**Comment by rajdeepv** [comment]
Great! Thanks

**Comment by ma2t87** [comment]
I have the same issue with version 0.1.3  but working with 0.1.2
run on mac OSX

**Comment by rajdeepv** [comment]
@ma2t87 can you please share below details?
1. command you are running
2. Exact error log
