### ISSUE TITLE
Group by feature files

### ISSUE THREAD

**Issue by bhaskarsr** [rajdeepv/parallel_calabash#30]
Hi @rajdeepv rajdeep,
Does this support running the tests group by feature files ? I am aware that this does not hold good if the feature file tests sizes are different. But in my case, i have relatively same number of scenarios in each feature file. I can't divide the scenarios in one feature file across more than one device and run(in few functional modules of our app only).

**Comment by rajdeepv** [comment]
what command are you using?

**Comment by bhaskarsr** [comment]
I tried group-by-scenarios that helped me alot in executing other modules. But I for specific modules, I want to run the tests group by feature files by giving a set of tags.

**Comment by rajdeepv** [comment]
@bhaskarsr If you do not set group-by-scenarios, a feature file will be run on a single device.

**Comment by bhaskarsr** [comment]
Thank you @rajdeepv. I am closing this.
