### ISSUE TITLE
error: more than one device and emulator

### ISSUE THREAD

**Issue by bhaskarsr** [rajdeepv/parallel_calabash#32]
Hi @rajdeepv, Thanks for this wonderful solution. My test suites are running fine except that some times we get the error: 
 - waiting for device -
error: more than one device and emulator
which causes the execution fail. Are aware of this case ?
No change in the commands and it works on some machines without issues and fails some times on some machines.

**Comment by rajdeepv** [comment]
Are you using any direct adb command in your tests scripts? If yes, consider replacing it with calabash provided adb_command method

**Comment by bhaskarsr** [comment]
Thanks Rajdeep. Its working now. Infact I was using adb command in my scripts. Thanks for letting  me know.
