### ISSUE TITLE
Reports dont load screenshots when directory default is changed

### ISSUE THREAD

**Issue by mbnetobr** [rajdeepv/parallel_calabash#8]
When i'm change directory of reports on config.yml, screenshots are not loaded.

My config.yml 
default: --format html --out reports\Automation_report_<%= ENV['TEST_PROCESS_NUMBER'] %>_<%= ENV['DEVICE_INFO'] %>.html --format pretty

The report is visible with layout brokened when link to open screenshot is tapped
![1](https://cloud.githubusercontent.com/assets/10273861/7454399/44cd39a4-f241-11e4-9f2a-7aa485296eb3.jpg)

ps: I'm think the problem occurs only on windows

**Comment by rajdeepv** [comment]
Does this work fine when you run tests in series after changing directory default? i mean without using parallel_calabash

**Comment by mbnetobr** [comment]
I'm understand you think the problem occurs with calabash gem.

Yes, the problem occurs with "calabash-android run ...."

I'm close this issue and open another on calabash git hub
